-- pcall(pcall, f)
-- the question is:
-- is the possible to propagate error outside pcall

local status, error = pcall(function() error("my error") end)
print(status, error)